name: Deploy Frontend to S3 Bucket

# Define trigger
on:
  push:
    branches:
      - main

# Define variables
env:
  AWS_REGION: <ap-northeast-2>
  IAM_ROLE_ARN: arn:aws:iam::123456789012:role/S3UpdateRole  # Replace with the IAM role ARN

# Define actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        role-duration-seconds: 900  # Adjust as per your requirements
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Frontend to S3 Bucket
      run: |
        aws s3 sync . s3://your-bucket-name --delete --region ${{ env.AWS_REGION }}
