name: Test and Deploy CloudFormation Stack

# Define trigger
on:
  push:
    branches:
      - main
      - features

# Define variables
env:
  AWS_REGION: ap-northeast-2  # Replace with your desired AWS region
  IAM_ROLE_ARN: arn:aws:iam::533267111936:role/CloudFormationAdminAccess  # Replace with the IAM role ARN
  STACK_NAME: CloudResumeChallengeStack  # Replace with your CloudFormation stack name
  TEMPLATE_PATH: backend/cloudformation/backend-template.yaml  # Replace with the path to your CloudFormation template

# Define actions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials for Validation
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        # role-duration-seconds: 900  # Adjust as per your requirements
        aws-region: ${{ env.AWS_REGION }}

    - name: Validate CloudFormation template
      run: aws cloudformation validate-template --template-body file://${{ env.TEMPLATE_PATH }}
      env:
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Configure AWS credentials for Deployment
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        role-duration-seconds: 900  # Adjust as per your requirements
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: aws cloudformation deploy --template-file ${{ env.TEMPLATE_PATH }} --stack-name ${{ env.STACK_NAME }} --capabilities CAPABILITY_NAMED_IAM
